### ISSUE TITLE
CloudFlare API request limits

### ISSUE THREAD

**Issue by ComradePashka** [jamesryanbell/cloudflare#45]
Hi James!
First of all thank you for your job 👍 

I am programming sort of CRM which should work with the CloudFlare bulk actions and so should avoid CF limits. I thought about queuing API requests, counting their total count, start-end delta and use delays between calls. It looks like the best place to do so is at API->request() method due to inheritence of API class to all other. But it looks like there's no way to extend/modify this code except forking from your repository (and it's not best idea).
Maybe I just missed important part about error handling and cases for CF limits.
What is your best practice to handle CF request limits?
Thank you.

**Comment by TangRufus** [comment]
In order to change ``Cloudflare\Api::request`` behaviour, I could only run script to change all subclass of ``Cloudflare\Api`` to subclass my patched version. Example [here](https://github.com/Typisttech/cloudflare-wp-api).

It would be great if we can inject the client at runtime. Any chance the next major version would support this?

Thanks!

**Comment by jamesryanbell** [comment]
Thanks @TangRufus, I am currently thinking about the next major release so I will factor this in. I don't have an ETA on that release currently.
